/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as CheckoutSlugRouteImport } from './routes/checkout/$slug'
import { Route as CheckoutVerifyRouteImport } from './routes/checkout/verify'
import { Route as DownloadTokenRouteImport } from './routes/download/$token'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as AdminProductIdRouteImport } from './routes/admin/product.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoversProductIdRouteImport } from './routes/api/covers/$productId'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as CheckoutTransferOrderIdRouteImport } from './routes/checkout/transfer.$orderId'
import { Route as ApiAdminProofOrderIdRouteImport } from './routes/api/admin/proof.$orderId'
import { Route as ApiFilesDownloadTokenRouteImport } from './routes/api/files/download.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutVerifyRoute = CheckoutVerifyRouteImport.update({
  id: '/checkout/verify',
  path: '/checkout/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadTokenRoute = DownloadTokenRouteImport.update({
  id: '/download/$token',
  path: '/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversProductIdRoute = ApiCoversProductIdRouteImport.update({
  id: '/api/covers/$productId',
  path: '/api/covers/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTransferOrderIdRoute = CheckoutTransferOrderIdRouteImport.update({
  id: '/checkout/transfer/$orderId',
  path: '/checkout/transfer/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProofOrderIdRoute = ApiAdminProofOrderIdRouteImport.update({
  id: '/api/admin/proof/$orderId',
  path: '/api/admin/proof/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDownloadTokenRoute = ApiFilesDownloadTokenRouteImport.update({
  id: '/api/files/download/$token',
  path: '/api/files/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/verify': typeof CheckoutVerifyRoute
  '/download/$token': typeof DownloadTokenRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$productId': typeof ApiCoversProductIdRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/checkout/transfer/$orderId': typeof CheckoutTransferOrderIdRoute
  '/api/admin/proof/$orderId': typeof ApiAdminProofOrderIdRoute
  '/api/files/download/$token': typeof ApiFilesDownloadTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/verify': typeof CheckoutVerifyRoute
  '/download/$token': typeof DownloadTokenRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$productId': typeof ApiCoversProductIdRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/checkout/transfer/$orderId': typeof CheckoutTransferOrderIdRoute
  '/api/admin/proof/$orderId': typeof ApiAdminProofOrderIdRoute
  '/api/files/download/$token': typeof ApiFilesDownloadTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/verify': typeof CheckoutVerifyRoute
  '/download/$token': typeof DownloadTokenRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$productId': typeof ApiCoversProductIdRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/checkout/transfer/$orderId': typeof CheckoutTransferOrderIdRoute
  '/api/admin/proof/$orderId': typeof ApiAdminProofOrderIdRoute
  '/api/files/download/$token': typeof ApiFilesDownloadTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/transfers'
    | '/checkout/$slug'
    | '/checkout/verify'
    | '/download/$token'
    | '/guides/$slug'
    | '/admin/'
    | '/guides/'
    | '/admin/product/$id'
    | '/api/auth/$'
    | '/api/covers/$productId'
    | '/api/paystack/webhook'
    | '/checkout/transfer/$orderId'
    | '/api/admin/proof/$orderId'
    | '/api/files/download/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/transfers'
    | '/checkout/$slug'
    | '/checkout/verify'
    | '/download/$token'
    | '/guides/$slug'
    | '/admin'
    | '/guides'
    | '/admin/product/$id'
    | '/api/auth/$'
    | '/api/covers/$productId'
    | '/api/paystack/webhook'
    | '/checkout/transfer/$orderId'
    | '/api/admin/proof/$orderId'
    | '/api/files/download/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/transfers'
    | '/checkout/$slug'
    | '/checkout/verify'
    | '/download/$token'
    | '/guides/$slug'
    | '/admin/'
    | '/guides/'
    | '/admin/product/$id'
    | '/api/auth/$'
    | '/api/covers/$productId'
    | '/api/paystack/webhook'
    | '/checkout/transfer/$orderId'
    | '/api/admin/proof/$orderId'
    | '/api/files/download/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CheckoutVerifyRoute: typeof CheckoutVerifyRoute
  DownloadTokenRoute: typeof DownloadTokenRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoversProductIdRoute: typeof ApiCoversProductIdRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  CheckoutTransferOrderIdRoute: typeof CheckoutTransferOrderIdRoute
  ApiAdminProofOrderIdRoute: typeof ApiAdminProofOrderIdRoute
  ApiFilesDownloadTokenRoute: typeof ApiFilesDownloadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/verify': {
      id: '/checkout/verify'
      path: '/checkout/verify'
      fullPath: '/checkout/verify'
      preLoaderRoute: typeof CheckoutVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$token': {
      id: '/download/$token'
      path: '/download/$token'
      fullPath: '/download/$token'
      preLoaderRoute: typeof DownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$productId': {
      id: '/api/covers/$productId'
      path: '/api/covers/$productId'
      fullPath: '/api/covers/$productId'
      preLoaderRoute: typeof ApiCoversProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/transfer/$orderId': {
      id: '/checkout/transfer/$orderId'
      path: '/checkout/transfer/$orderId'
      fullPath: '/checkout/transfer/$orderId'
      preLoaderRoute: typeof CheckoutTransferOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/proof/$orderId': {
      id: '/api/admin/proof/$orderId'
      path: '/api/admin/proof/$orderId'
      fullPath: '/api/admin/proof/$orderId'
      preLoaderRoute: typeof ApiAdminProofOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/download/$token': {
      id: '/api/files/download/$token'
      path: '/api/files/download/$token'
      fullPath: '/api/files/download/$token'
      preLoaderRoute: typeof ApiFilesDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductIdRoute: AdminProductIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CheckoutVerifyRoute: CheckoutVerifyRoute,
  DownloadTokenRoute: DownloadTokenRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoversProductIdRoute: ApiCoversProductIdRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  CheckoutTransferOrderIdRoute: CheckoutTransferOrderIdRoute,
  ApiAdminProofOrderIdRoute: ApiAdminProofOrderIdRoute,
  ApiFilesDownloadTokenRoute: ApiFilesDownloadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
